### PR TITLE
v0.30.1-rc1

### PR DESCRIPTION
**Pull request by dehann**
Hi @Affie , did you want to add anything to v0.30.1, or can the next PRs go to v0.30.2?

### CODE REVIEW

**Comment by dehann** [comment]
I am worried about 
- #1570 

So will look into that bit later today if can.

**Comment by dehann** [comment]
Caesar tests also seem to be failing more often on IIF master.  I get the sense that some of the recent changes may have upset the multihypo code with silent bug somewhere.

**Comment by Affie** [comment]
It can go into the next, but master broke from something upstream (i think)

**Comment by Affie** [comment]
Technically parametric has a bug in with the return types, but if you are in a hurry for something you can tag.

**Comment by dehann** [comment]
Looks like it has something to do with `getSolverParams(fg).useMsgLikelihoods = true`.  MWE:

```julia
using IncrementalInference

fg = generateGraph_CaesarRing1D()
getSolverParams(fg).useMsgLikelihoods = true

solveGraph!(fg)
```

**Comment by dehann** [comment]
useMsgLikelihoods uses `approxDeconv`, and I wonder if all that code got updated for Tangents vs Points in the new ArrayPartition work.

**Pull request merged**
