### PR TITLE
towards passthrough 'sampling',

### PR DESCRIPTION
**Pull request by dehann**
likely easier as part of v0.25

### CODE REVIEW

**Comment by dehann** [comment]
need for testing separately captured in #1306

**Comment by dehann** [comment]
hi @Affie just fyi that i will be merging this soon. contains a bunch of little fixes on vectorP

**Comment by Affie** [comment]
sure, go for it

**Comment by dehann** [comment]
cool, just note that something new is wrong with getnullhypo, will debug that in a new branch.

**Pull request merged**
