### PR TITLE
Update residual in _solveLambdaNumeric optim

### PR DESCRIPTION
**Pull request by Affie**
I missed the dots. I kept missing it with CalcFactos also.

### CODE REVIEW

**Review by dehann — APPROVED** [review]
hi, should be fine to broadcast thanks!

**Comment by Affie** [comment]
It's hard to know what will be faster without benchmarking. Since optim works with a single scalar cost variable, I dought it will make any difference. 
That being said, I think there is still a place for `CalcFactor.residual`, but for more specialised cases.

**Comment by Affie** [comment]
julia 1.6 beta test only fails because of random numerical test failure. 1.5 passes, so will merge.

**Comment by dehann** [comment]
HI @Affie , just to reaffirm this, add a +1 or -1 when you read this

> I think there is still a place for CalcFactor.residual, but for more specialised cases.

Agree, I think there will be specialized cases where in-place memory for `residual` will be needed.  Understand the type definition on `residual` is only near runtime.  I think this will be easier to sort out once CPT, CCW, FMd, CalcFactor are better consolidated and all factors are converted to the single definition.

**Pull request merged**
