### PR TITLE
Fixes for abstraction

### PR DESCRIPTION
**Pull request by GearsAD**

### CODE REVIEW

**Comment by GearsAD** [comment]
FYI @Affie

**Comment by Affie** [comment]
@dehann I would suggest that we take a smaller step like this and then do the cliqSubFg in a separate PR. DFG can provide the conversions quite easily for now.

**Comment by dehann** [comment]
merge this first and then fix the likely conflicts with #369

**Comment by Affie** [comment]
> merge this first and then fix the likely conflicts with #369

Currently, there is no conflicts. may change if this pr changes same files as #369

**Pull request merged**
