### PR TITLE
Sandbox optimization on manifold

### PR DESCRIPTION
**Pull request by Affie**
Here is my sanbox on manifold optimization. I updated an old attempt on Optim.jl to use un/coords and actually got it running.

### CODE REVIEW

**Review by dehann — APPROVED** [review]
Looks good to me thanks!  flatten might the better way to transition the serialization stuff for Manifolds.jl types

**Comment by Affie** [comment]
I tested at pi and it's not working properly there.

**Comment by Affie** [comment]
I'm merging this, just to have it in the latest master to work from. It can be deleted later.

**Comment by dehann** [comment]
sounds good thanks, this sandbox is going to help a lot!

**Pull request merged**
