### PR TITLE
WIP, Monitor parametric csms and cleanly exit on fail

### LINKED ISSUE #753: add watchdog to auto-stop dormant CSM tasks
If during `solveTree!` something goes wrong and there is no activity anywhere on the tree (all CSMs are stuck or closed out) then an autostop on all tasks  -- perhaps self terminate on watchdog -- could be very useful, rather than having to close the entire Julia context to regain control of threads/processes.

### PR DESCRIPTION
**Pull request by Affie**
@dehann, this got left behind somehow. I'll wait for #459 and then see if it still works. 
it was my solution to #753

For future self - look at local changes in that branch

### CODE REVIEW

**Comment by dehann** [comment]
Will ask this to be added for the nonparametric case soon too please :-) almost there on 459...

**Comment by dehann** [comment]
Ah also, this is not a watchdog timer in the same sense -- I read this as termination when one CSM fails.  Idea in #753 also includes a further case where a CSM goes unresponsive without an error occurring, where a watchdog then interrupts and terminates the entire solve is this PR is doing.

**Comment by Affie** [comment]
> this is not a watchdog timer in the same sense -- I read this as termination when one CSM fails

Yes, Its clean termination on fail mechanism. I terminated manually so far on stalls. I went for the global approach to monitoring and not in the cliques, but the design is not completed yet.

**Comment by dehann** [comment]
xref: https://github.com/JuliaRobotics/IncrementalInference.jl/issues/443#issuecomment-677702617

**Pull request closed without merging**
