### PR TITLE
towards solveTree! with unique solveKey

### PR DESCRIPTION
**Pull request by dehann**
MWE for #1219 
```julia
solveTree!(fg, solveKey=:greatscott21)
```

cc @jim-hill-r , work in progress to make this possible.

### CODE REVIEW

**Comment by dehann** [comment]
xref #1229

**Comment by GearsAD** [comment]
🎉

**Comment by dehann** [comment]
HI @jim-hill-r , im merging this.  Might still have a bug or two.  I'm at the point of diminishing returns and would rather keep going on getting you test scripts and find bugs in aggregate.  

I did have to break something small with parametric solve, but the particular API is still in development and asked @Affie to separately include that with his ongoing work on finishing the parametric consolidation.  That issue can be followed at #1229  if interested.

**Comment by dehann** [comment]
THis will be available in v0.23.2

**Pull request merged**
