### PR TITLE
Towards fixing parametric

### PR DESCRIPTION
**Pull request by Affie**
fix initParametricFrom!

### CODE REVIEW

**Review by dehann — APPROVED** [review]
I read through as carefully i can, looks right.  I just want to go clean up so much code here.  Thanks for PR, i'll also will merge

**Comment by dehann** [comment]
Actually, @Affie , could please fix the CI failures before we merge please.

**Review by dehann — COMMENTED** [review]
CI

**Comment by Affie** [comment]
close #1521

**Comment by dehann** [comment]
very cool, thanks!

**Pull request merged**
