### PR TITLE
try quick fix on #1136

### LINKED ISSUE #1136: Attempt to access 0-element Vector{Float64} at index [1]
Just capturing so long, will investigate further when I have a chance:
-  All masters and julia 1.6.0-beta1
- Tried to solve loaded fg
```
    nested task error: BoundsError: attempt to access 0-element Vector{Float64} at index [1]
    Stacktrace:
      [1] getindex
        @ ./array.jl:801 [inlined]
      [2] calcPPE(var::DFGVariable{Point2}, varType::Point2; method::Type{MeanMaxPPE}, solveKey::Symbol)
        @ IncrementalInference ~/.julia/dev/IncrementalInference/src/FGOSUtils.jl:204
      [3] calcPPE(var::DFGVariable{Point2}; method::Type{MeanMaxPPE}, solveKey::Symbol)
        @ IncrementalInference ~/.julia/dev/IncrementalInference/src/FGOSUtils.jl:215
      [4] setPPE!(subfg::LightDFG{SolverParams, DFGVariable, DFGFactor}, label::Symbol, solveKey::Symbol, method::Type{MeanMaxPPE}, newPPEVal::Nothing)
        @ IncrementalInference ~/.julia/dev/IncrementalInference/src/FGOSUtils.jl:552
      [5] setPPE!
        @ ~/.julia/dev/IncrementalInference/src/FGOSUtils.jl:550 [inlined]
      [6] updateFromSubgraph_StateMachine(csmc::CliqStateMachineContainer{BayesTreeNodeData, LightDFG{SolverParams, DFGVariable, DFGFactor}, LightDFG{SolverParams, DFGVariable, DFGFactor}, MetaBayesTree})
        @ IncrementalInference ~/.julia/dev/IncrementalInference/src/CliqueStateMachine.jl:751
      [7] (::StateMachine{CliqStateMachineContainer})(userdata::CliqStateMachineContainer{BayesTreeNodeData, LightDFG{SolverParams, DFGVariable, DFGFactor}, LightDFG{SolverParams, DFGVariable, DFGFactor}, MetaBayesTree}, timeout::Nothing; pollinterval::Float64, breakafter::Function, verbose::Bool, verbosefid::Base.TTY, verboseXtra::IncrementalInference.CliqStatus, iterlimit::Int64, injectDelayBefore::Nothing, recordhistory::Bool, housekeeping_cb::IncrementalInference.var"#377#379"{IncrementalInference.TreeClique})
        @ FunctionalStateMachine ~/.julia/packages/FunctionalStateMachine/2JZFG/src/StateMachine.jl:82
      [8] initStartCliqStateMachine!(dfg::LightDFG{SolverParams, DFGVariable, DFGFactor}, tree::MetaBayesTree, cliq::IncrementalInference.TreeClique, timeout::Nothing; oldcliqdata::BayesTreeNodeData, verbose::Bool, verbosefid::Base.TTY, drawtree::Bool, show::Bool, incremental::Bool, limititers::Int64, upsolve::Bool, downsolve::Bool, recordhistory::Bool, delay::Bool, logger::Base.CoreLogging.SimpleLogger, solve_progressbar::ProgressMeter.ProgressUnknown, algorithm::Symbol)
        @ IncrementalInference ~/.julia/dev/IncrementalInference/src/CliqueStateMachine.jl:63
      [9] tryCliqStateMachineSolve!(dfg::LightDFG{SolverParams, DFGVariable, DFGFactor}, treel::MetaBayesTree, cliqKey::Int64, timeout::Nothing; oldtree::MetaBayesTree, verbose::Bool, verbosefid::Base.TTY, drawtree::Bool, limititers::Int64, downsolve::Bool, incremental::Bool, delaycliqs::Vector{Symbol}, recordcliqs::Vector{Symbol}, solve_progressbar::ProgressMeter.ProgressUnknown, algorithm::Symbol)
        @ IncrementalInference ~/.julia/dev/IncrementalInference/src/SolverAPI.jl:110
     [10] (::IncrementalInference.var"#433#436"{MetaBayesTree, Bool, Bool, Base.TTY, Bool, Bool, Vector{Symbol}, Vector{Symbol}, Symbol, LightDFG{SolverParams, DFGVariable, DFGFactor}, MetaBayesTree, Nothing, ProgressMeter.ProgressUnknown, Int64, Int64})()
        @ IncrementalInference ./task.jl:406
```

### PR DESCRIPTION
**Pull request by dehann**
Might need backports

### CODE REVIEW

**Comment by Affie** [comment]
Looks good, it needs something similar for multiprocessor. 
What bothers me a bit is that fixing this will hide another potential error.

**Comment by dehann** [comment]
> needs something similar for multiprocessor

I'd have to look for it, or please add if you have easy recall on where those lines of code are.

> another potential error

oops, which error would that be?

**Comment by Affie** [comment]
> oops, which error would that be?

See https://github.com/JuliaRobotics/IncrementalInference.jl/issues/1136#issuecomment-768328530 
There were no factors on the specific frontal.

**Comment by Affie** [comment]
> I'd have to look for it, or please add if you have easy recall on where those lines of code are.

I added as I understand, please review.

**Review by Affie — COMMENTED** [review]
I added same on multiproc

**Comment by Affie** [comment]
ping @dehann

**Comment by dehann** [comment]
hi @Affie , we going back and forth.  I think we can merge although I am not sure about the concerns you raised.  It looks like you cleared them with the later commit.  If you are happy, please go ahead and merge this PR.

**Comment by Affie** [comment]
The concerns are about an underlying issue that causes the point to be zero. (that should not happen in this case) 
There was a warning a while back that I think is related. I don't know if it was taken out or redirected to the logger, I'll try and find it. The problem is to find MWE that shows this. Give me some time on this one as I don't want to potentially hide an issue.

**Comment by dehann** [comment]
okay, understood thanks!

**Comment by Affie** [comment]
Ok, I kind of remember (70%) the waning being from here:
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/4bad101cbf54e2aa2362dd5cb6cb1eaa8641c282/src/GraphProductOperations.jl#L81

**Comment by dehann** [comment]
error #1136 was caused by keyword arguments in AMP.manifoldProduct not having enough content for broadcasting.  A few alternate PRs should have fixed the issue.  The attempted fix in this PR is not valid, and would introduce an unwanted error.

**Pull request closed without merging**
