### PR TITLE
Develop [ing something??]

### PR DESCRIPTION
**Pull request by dehann**

### CODE REVIEW

**Comment by dehann** [comment]
if DFG v0.8.0 has a breaking change, we should perhaps lift the DFG minimum requirement to v0.8.0?

**Comment by Affie** [comment]
Minor version will need to be bumped.

**Comment by dehann** [comment]
now requires JuliaRobotics/DistributedFactorGraphs.jl#442 for IIF tests to pass

**Comment by dehann** [comment]
help fix JuliaRobotics/DistributedFactorGraphs.jl#441

**Comment by dehann** [comment]
> all will use the same wrapper.

we all using CCW and that keeps the code maintenance down too :-)

**Comment by Affie** [comment]
> if DFG v0.8.0 has a breaking change, we should perhaps lift the DFG minimum requirement to v0.8.0?

I had to put v0.7 back because of a weird travis issue, but yes. It should be removed

**Pull request merged**
