### PR TITLE
Use getManifold on factors

### PR DESCRIPTION
**Pull request by Affie**
Hi @dehann, I just want to make sure `getManifold` on factors is the intended way to go

### CODE REVIEW

**Review by dehann — APPROVED** [review]
HI @Affie , yeah I think `getManifold(fcttype)` is the way to go.  For transition or "easier" cases we can use `ManifoldFactor/Prior` but in general we will probably require the user to implement:
```julia
IIF.getManifold(::InstanceType{MyAwesomeFactor}) = Euclidean(7)
```

since resolving the Manifold is better resolved with dispatch rather than storing the manifold each time as a field in the factor.  The dispatch should be plenty sufficient.

**Comment by dehann** [comment]
Hi @Affie , just also note that I expect the tests to pass, so just make sure everything is fixed before merging this.

**Comment by Affie** [comment]
The tests were broken before this by AMP in https://github.com/JuliaRobotics/ApproxManifoldProducts.jl/pull/107/files#r671323810

**Comment by Affie** [comment]
I see #1309 should fix this.

**Pull request merged**
